services:
  postgres:
    image: postgres
    container_name: my_postgres
    env_file: dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: dev.env

  frontend:   # Имя сервиса
    image: nginx:latest
    volumes:
      - ../shortify-frontend/config/:/etc/nginx/
      # - "/etc/letsencrypt/live/shorty.su/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro"
      # - "/etc/letsencrypt/live/shorty.su/privkey.pem:/etc/nginx/certs/privkey.pem:ro"
    build:
      context: ../shortify-frontend       # Текущая директория как контекст сборки
      dockerfile: Dockerfile  # Имя Dockerfile
    ports:
      - '80:80'
      - '443:443'  # Проброс порта контейнера на локальный порт

volumes:
  postgres-data:

networks:
  webnet:
    external: true
