services:
  postgres:
    image: postgres
    container_name: my_postgres
    env_file: dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: dev.env
    restart: always

  frontend:   # Имя сервиса
    image: nginx:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ../shortify-frontend/config/:/etc/nginx/
    build:
      context: ../shortify-frontend       # Текущая директория как контекст сборки
      dockerfile: Dockerfile  # Имя Dockerfile
    ports:
      - "80:80"  # Проброс порта контейнера на локальный порт
    restart: always

volumes:
  postgres-data:

networks:
  webnet:
    external: true
